version: "3"

networks:
  default:
    external:
      name: nginx-proxy

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: $USERNAME_DB
      MONGO_INITDB_ROOT_PASSWORD: $PASSWORD_DB

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: $USERNAME_DB
      ME_CONFIG_MONGODB_ADMINPASSWORD: $PASSWORD_DB
